{{- if (not .Values.inPodPostgres.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "db.fullname" . }}
  labels:
    app: {{ template "postgresql.name" . }}
    chart: {{ template "fullname" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  dbPassword: {{ randAlphaNum 10 | b64enc | quote }}
{{- end }}
